//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangVangBacDaQuy.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUBAOCAOTONKHO
    {
        public string MACHITIETBAOCAOTONKHO { get; set; }
        public string SOPHIEU { get; set; }
        public string MASP { get; set; }
        public int TONDAU { get; set; }
        public int SlBAN { get; set; }
        public int SLMUA { get; set; }
        public int TONCUOI { get; set; }
    
        public virtual PHIEUBAOCAOTONKHO PHIEUBAOCAOTONKHO { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
