//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangVangBacDaQuy.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.PhieuBans = new HashSet<PhieuBan>();
            this.PhieuMuas = new HashSet<PhieuMua>();
        }
    
        public int MaND { get; set; }
        public string TenND { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public int MaQH { get; set; }
    
        public virtual QuyenHan QuyenHan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuBan> PhieuBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMua> PhieuMuas { get; set; }

        private static NguoiDung _Logged;
        public static NguoiDung Logged
        {
            get
            {
                if (_Logged == null)
                    _Logged = new NguoiDung();
                return _Logged;
            }
            set
            {
                _Logged = value;
            }
        }
    }
}
