//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangVangBacDaQuy.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string MANHOM { get; set; }
    
        public virtual NHOMNGUOIDUNG NHOMNGUOIDUNG { get; set; }
    }
}
