//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangVangBacDaQuy.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuMua()
        {
            this.ChiTietPhieuMuas = new HashSet<ChiTietPhieuMua>();
        }
    
        public string MaPhieu { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public int MaNCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuMua> ChiTietPhieuMuas { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
