//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangVangBacDaQuy.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUAHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUMUAHANG()
        {
            this.CHITIETPHIEUMUAHANGs = new HashSet<CHITIETPHIEUMUAHANG>();
        }
    
        public string SOPHIEU { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public string MANCC { get; set; }
        public decimal TONGTIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUMUAHANG> CHITIETPHIEUMUAHANGs { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
