//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangVangBacDaQuy.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETPHIEUBANHANGs = new HashSet<CHITIETPHIEUBANHANG>();
            this.CHITIETPHIEUBAOCAOTONKHOes = new HashSet<CHITIETPHIEUBAOCAOTONKHO>();
            this.CHITIETPHIEUMUAHANGs = new HashSet<CHITIETPHIEUMUAHANG>();
        }
    
        public string MASP { get; set; }
        public string MALOAISP { get; set; }
        public string TENSP { get; set; }
        public decimal DONGIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUBANHANG> CHITIETPHIEUBANHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUBAOCAOTONKHO> CHITIETPHIEUBAOCAOTONKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUMUAHANG> CHITIETPHIEUMUAHANGs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
