//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangVangBacDaQuy.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VBDQEntityDBEntities : DbContext
    {
        public VBDQEntityDBEntities()
            : base("name=VBDQEntityDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETPHIEUBANHANG> CHITIETPHIEUBANHANGs { get; set; }
        public virtual DbSet<CHITIETPHIEUBAOCAOTONKHO> CHITIETPHIEUBAOCAOTONKHOes { get; set; }
        public virtual DbSet<CHITIETPHIEUMUAHANG> CHITIETPHIEUMUAHANGs { get; set; }
        public virtual DbSet<CHUCNANG> CHUCNANGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHOMNGUOIDUNG> NHOMNGUOIDUNGs { get; set; }
        public virtual DbSet<PHANQUYEN> PHANQUYENs { get; set; }
        public virtual DbSet<PHIEUBANHANG> PHIEUBANHANGs { get; set; }
        public virtual DbSet<PHIEUBAOCAOTONKHO> PHIEUBAOCAOTONKHOes { get; set; }
        public virtual DbSet<PHIEUMUAHANG> PHIEUMUAHANGs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
